# Generated by Django 4.1.7 on 2023-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_scrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employment Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_benefits',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Benefits'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pay'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pay_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pay Type'),
        ),
    ]
