# Generated by Django 4.1.7 on 2023-03-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_scrapper_app', '0002_alter_job_employment_type_alter_job_job_benefits_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-modified', '-pay')},
        ),
    ]
