# Generated by Django 4.1.7 on 2023-03-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_board_scrapper_app', '0003_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pay',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Pay'),
        ),
    ]
